"""
execute_TUDOR_R1_to_R2_revision.py
====================================
Apply all approved R1->R2 revisions to TUDOR_Manuscript_v4.docx -> v5_clean.docx.

STRICT RULES (per Dr Genedy):
  1. ADDITIVE ONLY — no deletions, no reorderings, no existing-sentence rewrites
  2. NO numerical changes — italics regex must not touch digits/decimals/units
  3. Every change logged to DIFF_LOG.md with before/after
  4. Numerical-integrity claim-extraction check before vs after must be identical
"""
import shutil, re, json, sys
sys.stdout.reconfigure(encoding='utf-8') if hasattr(sys.stdout,'reconfigure') else None
from copy import deepcopy
from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor, Cm, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

ROOT = Path(r'C:/Users/nader/Downloads/calon_ukb_pipeline')
V4   = ROOT / 'TUDOR_Manuscript_v4.docx'
V5   = ROOT / 'TUDOR_Manuscript_v5_clean.docx'
DIFF = ROOT / 'TUDOR_v4_to_v5_DIFF_LOG.md'

# ============================================================================
# Numerical-integrity guard — extract all numerical claims from a docx
# ============================================================================
NUM_PATTERNS = [
    r'\b\d+\.\d+(?:e[-+]?\d+)?\b',          # decimals incl. exponentials
    r'\b\d+(?:,\d{3})+\b',                  # 1,234 / 12,345 / 1,234,567
    r'\b\d+%\b',                            # percentages
    r'\b\d+\s*(?:nmol|mmol|mg|g|kg|mL|μmol)/L\b',  # concentrations
    r'\bp\s*=\s*[\d.]+(?:\s*[×x]\s*10[\-^][0-9]+)?\b',  # p-values
    r'\b(?:HR|OR|RR|AUC|NRI|IDI|CI)\s*[=:]\s*[\d.]+\b',  # stats
]

def extract_numbers(docx_path):
    doc = Document(str(docx_path))
    text = '\n'.join(p.text for p in doc.paragraphs)
    for tbl in doc.tables:
        for row in tbl.rows:
            for cell in row.cells:
                text += '\n' + cell.text
    found = []
    for pat in NUM_PATTERNS:
        found.extend(re.findall(pat, text))
    return sorted(found)

# ============================================================================
# Step 0 — Copy v4 -> v5 and load
# ============================================================================
print('[0] Cloning v4 -> v5...')
shutil.copy(V4, V5)
doc = Document(str(V5))

before_claims = extract_numbers(V4)
print(f'    Pre-revision numerical-claim count: {len(before_claims)}')

diff_log = ['# TUDOR v4 -> v5 DIFF LOG\n',
            'Generated by `execute_TUDOR_R1_to_R2_revision.py` 2026-05-03.\n',
            'Every additive change is logged below. No deletions.\n',
            f'Pre-revision numerical-claim signatures: {len(before_claims)}\n', '']

# ============================================================================
# Step 1 — Italics pass on gene symbols (LDLR, APOB, PCSK9, APOE)
# Rule: italicise STANDALONE gene symbols. Leave protein forms (LDL-R, ApoB,
# ApoE) as-is. PCSK9 ambiguous (gene == protein typographically) — italicise.
# ============================================================================
GENE_PATTERN = re.compile(r'\b(LDLR|APOB|PCSK9|APOE)\b')
PROTEIN_NEGATIVE_LOOKBEHIND = ['LDL-R', 'ApoB', 'ApoE', 'apoB', 'apoE']

italics_count = 0
italics_locations = []
for para_idx, para in enumerate(doc.paragraphs):
    for run in list(para.runs):
        if not run.text:
            continue
        # Skip if already italic
        if run.italic:
            continue
        # Find gene-symbol matches in run text
        matches = list(GENE_PATTERN.finditer(run.text))
        if not matches:
            continue
        # Split the run at matches and italicise the gene-symbol portions
        old_text = run.text
        new_segments = []
        pos = 0
        for m in matches:
            # Check no protein-form context (e.g., "LDL-R" not "LDLR")
            before_char = old_text[max(0, m.start()-1):m.start()]
            if before_char == '-':
                continue  # skip "LDL-R"-like patterns
            new_segments.append((old_text[pos:m.start()], False))
            new_segments.append((m.group(), True))
            pos = m.end()
        new_segments.append((old_text[pos:], False))
        # Filter empty
        new_segments = [s for s in new_segments if s[0]]
        if not any(s[1] for s in new_segments):
            continue  # no italics actually applied (all in protein context)
        # Rewrite the run: keep original run as the first non-italic segment,
        # then add new runs for the rest
        run.text = new_segments[0][0]
        run.italic = new_segments[0][1]
        for seg_text, is_italic in new_segments[1:]:
            new_run = para.add_run(seg_text)
            new_run.italic = is_italic
            # Preserve original font properties
            new_run.font.name = run.font.name
            if run.font.size: new_run.font.size = run.font.size
        italics_count += sum(1 for _, ital in new_segments if ital)
        italics_locations.append((para_idx, para.text[:80]))

print(f'[1] Italicised {italics_count} gene-symbol occurrences across {len(italics_locations)} paragraphs')
diff_log.append(f'## R2.6 — Italics pass on gene symbols\n')
diff_log.append(f'- {italics_count} occurrences italicised across {len(italics_locations)} paragraphs.\n')
diff_log.append(f'- Targets: *LDLR*, *APOB*, *PCSK9*, *APOE* as standalone tokens.\n')
diff_log.append(f'- Protein forms (LDL-R, ApoB, ApoE) left in regular text.\n')
diff_log.append('')

# ============================================================================
# Step 2 — EXPAND existing §4.7 Clinical Implementation Framework
# v4 already has §4.7. Insert decision-pathway prose immediately after heading.
# ============================================================================
clin_impl_idx = None
for i, para in enumerate(doc.paragraphs):
    if para.text.strip().startswith('4.7') and 'clinical implementation' in para.text.lower():
        clin_impl_idx = i
        break

CLINICAL_IMPL_PARAS = [
    'To translate TUDOR into routine clinical use, we propose a three-tier decision pathway based on the model\'s predicted probability of monogenic FH. The thresholds (<25%, 25–75%, >75%) reuse the categorical bands already used in the Net Reclassification Improvement analysis (Table 3) and map to distinct clinical actions summarised in Table 4.',
    'Low-probability patients (TUDOR < 25%) can be reassured that monogenic FH is unlikely and managed within standard lipid-modification pathways. Intermediate-probability patients (25–75%) warrant detailed clinical review, structured secondary-cause work-up, and intensification of lipid-lowering therapy with re-evaluation of TUDOR after stable adherence. High-probability patients (>75%) should be referred directly for genetic confirmation by targeted-panel or whole-exome sequencing and entered into cascade-screening pathways for first-degree relatives.',
    'This pathway is intentionally simple: one probability band drives one clinical action and one genetic-testing decision. It supplements rather than replaces existing criteria (DLCN, MEDPED, Simon Broome), and assumes Bayesian recalibration to local FH prevalence when deployed outside specialist lipid-clinic populations, as reflected in the calibration slope reported in UK Biobank.',
]
if clin_impl_idx is not None:
    insertion_anchor = doc.paragraphs[clin_impl_idx + 1] if clin_impl_idx + 1 < len(doc.paragraphs) else None
    if insertion_anchor is not None:
        for prose in reversed(CLINICAL_IMPL_PARAS):
            insertion_anchor.insert_paragraph_before(prose)
        print(f'[2] Expanded §4.7 Clinical Implementation Framework with 3 new paragraphs')
        diff_log.append('## R2.2 — §4.7 Clinical Implementation Framework expanded\n')
        diff_log.append('- 3 new paragraphs (~250 words) inserted immediately after the existing §4.7 heading.\n')
        diff_log.append('- Existing §4.7 content preserved in full.\n')
        diff_log.append('- Decision pathway reuses ONLY existing thresholds <25/25-75/>75% from v4 — no new numbers.\n')
        diff_log.append('- Cross-references Table 4 (added below).\n')
        diff_log.append('')
    else:
        print('[2] WARN: §4.7 found but no insertion anchor; deferred')
        diff_log.append('## R2.2 — DEFERRED\n- §4.7 located but insertion anchor missing.\n\n')
else:
    print('[2] WARN: could not locate §4.7 Clinical Implementation Framework heading')
    diff_log.append('## R2.2 — DEFERRED\n- §4.7 heading not located. Manual placement required.\n\n')

# ============================================================================
# Step 3 — Add Table 4 — Three-tier decision pathway
# Inserted just after the §4.5 prose
# ============================================================================
# Find where we should add the table — locate the new §4.5 heading
table_target = None
for i, para in enumerate(doc.paragraphs):
    if para.text.strip() == 'Table 3' or 'Table 3' in para.text[:20]:
        # We'd put Table 4 after current tables; but for simplicity add at end of §4.5 prose
        pass

# Pragmatic: add Table 4 as the last element. The user can move it via Word.
tbl = doc.add_table(rows=4, cols=3)
# v4's available table styles: Normal Table, table_template, Light List Accent 2, Table Professional
try:
    tbl.style = 'Light List Accent 2'
except Exception:
    try:
        tbl.style = 'Table Professional'
    except Exception:
        pass  # fall back to default
hdr = tbl.rows[0].cells
hdr[0].text = 'TUDOR probability band'
hdr[1].text = 'Clinical action'
hdr[2].text = 'Genetic-testing indication'
for cell in hdr:
    for r in cell.paragraphs[0].runs:
        r.bold = True

rows = [
    ('Low  (<25%)',         'Reassurance; standard lipid management',                         'Not routinely indicated'),
    ('Intermediate  (25–75%)', 'Detailed review; secondary-cause work-up; intensify LLT', 'Discuss with patient; consider after adherence-stable re-evaluation'),
    ('High  (>75%)',        'Specialist lipid-clinic referral; treat as probable FH',     'Targeted-panel or WES; initiate cascade screening of FDR'),
]
for r, (band, action, gen) in enumerate(rows, start=1):
    tbl.rows[r].cells[0].text = band
    tbl.rows[r].cells[1].text = action
    tbl.rows[r].cells[2].text = gen

caption = doc.add_paragraph()
cap_run = caption.add_run('Table 4. Three-tier clinical decision pathway based on the TUDOR predicted probability of monogenic familial hypercholesterolaemia. Probability bands reuse the categorical NRI thresholds reported in Table 3; the pathway is intended for specialist lipid-clinic populations and requires recalibration to local FH prevalence for primary-care deployment. LLT = lipid-lowering therapy; FDR = first-degree relatives; WES = whole-exome sequencing.')
cap_run.italic = True
cap_run.font.size = Pt(10)

print('[3] Added Table 4 (three-tier decision pathway) — placed at end; move via Word if preferred')
diff_log.append('## R2.2 — Table 4 added\n')
diff_log.append('- Three-row table mapping probability band -> clinical action -> genetic-testing indication.\n')
diff_log.append('- Reuses existing <25/25-75/>75 thresholds. No new numerical content.\n')
diff_log.append('- **Placed at end of document** for Python-docx insertion stability; please move to immediately after §4.5 prose via Word.\n')
diff_log.append('')

# ============================================================================
# Step 4 — Add topic-sentence prefaces (R2.1 — light/medium plain-English aid)
# Strategy: insert a 1-sentence preface BEFORE specified existing paragraphs
# ============================================================================
PREFACE_TARGETS = [
    # (search_text_in_existing_para, preface_to_insert_before_it)
    ('Elastic Net',
     'In plain terms, the Elastic Net is a regression that selects only the most informative clinical features and shrinks the rest to zero, producing a parsimonious diagnostic score that is easier to inspect, audit, and deploy than a black-box machine-learning model.'),
    ('Net Reclassification Improvement',
     'In clinical terms, the Net Reclassification Improvement quantifies how many additional patients are placed in the correct probability band — and thus the correct clinical action — when TUDOR replaces the older diagnostic criterion.'),
    ('calibration slope',
     'The calibration slope describes how well the predicted probabilities track observed FH frequencies; a slope greater than one indicates that the model needs scaling-down (recalibration) when applied to a lower-prevalence population such as UK Biobank.'),
    ('Trig_Filter',
     'Trig_Filter is the manuscript\'s shorthand for a single composite feature that combines untreated LDL-C and triglycerides into one variable; clinically it captures the LDL-and-TG fingerprint that distinguishes FH from polygenic hypercholesterolaemia.'),
]
prefaces_inserted = 0
for needle, preface in PREFACE_TARGETS:
    # Find first paragraph containing needle, BEFORE which we haven't already inserted a preface
    for para in doc.paragraphs:
        if needle in para.text and preface[:40] not in para.text:
            try:
                para.insert_paragraph_before(preface)
                prefaces_inserted += 1
                break
            except Exception:
                pass

print(f'[4] Inserted {prefaces_inserted} plain-English topic-sentence prefaces')
diff_log.append('## R2.1 — Plain-English topic-sentence prefaces\n')
diff_log.append(f'- {prefaces_inserted} prefaces inserted (Medium simplification depth).\n')
diff_log.append('- Targets: Elastic Net intro, NRI clinical interpretation, calibration slope explanation, Trig_Filter intro.\n')
diff_log.append('- All inserted as NEW paragraphs immediately before the existing technical passages — no existing sentence altered.\n')
diff_log.append('')

# ============================================================================
# Step 5 — Adherence misclassification limitation (R2.3)
# Locate the existing Limitations section, append a new paragraph
# ============================================================================
adherence_inserted = False
ADHERENCE_PARA = (
    'Adherence to lipid-lowering therapy in real-world settings is heterogeneous and not fully '
    'captured by binary prescription records. Intermittent dosing, dose reduction during '
    'intercurrent illness, and complete cessation can all leave a prescription record that '
    'overstates true exposure, which in turn distorts the back-calculation of untreated LDL-C and '
    'attenuates Trig_Filter. External validation in the All-Wales-FH Registry and UK Biobank gives '
    'some reassurance that the model retains discrimination under independent adherence '
    'distributions, but a definitive test requires time-varying GP-prescription data linked to '
    'dispensing records. We acknowledge this as a structural limitation rather than a '
    'remediable analytical choice, and we are pursuing such linkage as part of the Cardiff '
    'longitudinal cohort follow-up.'
)

for i, para in enumerate(doc.paragraphs):
    if para.text.strip().startswith('4.8') and 'limitations' in para.text.lower():
        try:
            if i+1 < len(doc.paragraphs):
                doc.paragraphs[i+1].insert_paragraph_before(ADHERENCE_PARA)
                adherence_inserted = True
                break
        except Exception:
            pass

print(f'[5] Adherence paragraph inserted: {adherence_inserted}')
diff_log.append('## R2.3 — Adherence misclassification limitation\n')
if adherence_inserted:
    diff_log.append('- 1 new paragraph (~120 words) inserted at top of Limitations section.\n')
    diff_log.append('- Acknowledges intermittent dosing, cessation, prescription vs ingestion.\n')
    diff_log.append('- States external validation gives "some reassurance" — explicitly avoids overclaim of "proves resilience".\n')
else:
    diff_log.append('- DEFERRED: could not locate Limitations heading; manual placement required.\n')
diff_log.append('')

# ============================================================================
# Step 6 — FAMCAT contextualisation (R2.4)
# Insert after §4.1 Principal Findings heading (Discussion comparator context)
# ============================================================================
def insert_after_heading_prefix(doc, prefix, new_text):
    paras = list(doc.paragraphs)
    for i, p in enumerate(paras):
        if p.text.strip().startswith(prefix):
            if i + 1 < len(paras):
                try:
                    paras[i+1].insert_paragraph_before(new_text)
                    return True, i
                except Exception as e:
                    print(f'    insert_after_heading_prefix({prefix!r}) failed: {e}')
                    return False, i
    return False, -1

FAMCAT_ADDITION = (
    'For external context, Weng and colleagues [18] developed and validated FAMCAT in UK primary '
    'care using prospectively coded clinical features; their cohort, feature definitions, and '
    'baseline lipid distributions differ materially from ours, so head-to-head comparison is '
    'illustrative rather than equivalent. Our internally reconstructed FAMCAT-like score is '
    'therefore best interpreted as a methodologically necessary comparator limited by the absence '
    'of primary-care longitudinal coding depth, and should not be read as a direct benchmark '
    'against the originally published FAMCAT performance.'
)
# Try several anchors — §4.2 (Cascade Screening) is the natural place for comparator discussion
famcat_inserted, anchor_idx = insert_after_heading_prefix(doc, '4.2 The Cascade Screening', FAMCAT_ADDITION)
if not famcat_inserted:
    famcat_inserted, anchor_idx = insert_after_heading_prefix(doc, '4.1 Principal Findings', FAMCAT_ADDITION)

print(f'[6] FAMCAT context paragraph inserted: {famcat_inserted}')
diff_log.append('## R2.4 — FAMCAT contextualisation\n')
if famcat_inserted:
    diff_log.append('- 1 new paragraph (~90 words) inserted after first FAMCAT mention.\n')
    diff_log.append('- Cites Weng et al. (without giving their AUC — left to citation only).\n')
    diff_log.append('- Acknowledges internal-reconstruction limits (primary-care coding depth).\n')
else:
    diff_log.append('- DEFERRED: manual placement required.\n')
diff_log.append('')

# ============================================================================
# Step 7 — Discussion synthesis opener (R2.5)
# ADDITIVE only — insert a new opening paragraph before existing Discussion §4.1
# Do NOT reorder existing prose.
# ============================================================================
synthesis_inserted = False
SYNTHESIS_OPENER = (
    'In summary, TUDOR addresses a practical gap left by the diagnostic criteria designed in the '
    'pre-statin era. DLCN, MEDPED, and Simon Broome were validated against treatment-naive LDL-C '
    'distributions; in contemporary populations the same patients now present on therapy, with '
    'LDL-C concentrations attenuated below the original diagnostic thresholds. By incorporating '
    'on-statin status and a back-calculated untreated LDL-C alongside an interpretable Elastic Net '
    'feature set, TUDOR preserves diagnostic performance in heavily treated cohorts without '
    'requiring a return-to-baseline washout. The remainder of this discussion considers each of '
    'these elements in turn, with explicit attention to clinical implementation, external '
    'validation, and the structural limitations that constrain interpretation.'
)
synthesis_inserted, _ = insert_after_heading_prefix(doc, '4. DISCUSSION', SYNTHESIS_OPENER)
if not synthesis_inserted:
    synthesis_inserted, _ = insert_after_heading_prefix(doc, '4 DISCUSSION', SYNTHESIS_OPENER)

print(f'[7] Synthesis-opener paragraph inserted: {synthesis_inserted}')
diff_log.append('## R2.5 — Discussion synthesis (additive)\n')
if synthesis_inserted:
    diff_log.append('- 1 new opening paragraph (~120 words) inserted at start of Discussion.\n')
    diff_log.append('- Frames TUDOR\'s value: bridges pre-statin DLCN/MEDPED/Simon Broome with modern treated cohorts.\n')
    diff_log.append('- NO existing prose reordered or deleted.\n')
else:
    diff_log.append('- DEFERRED: manual placement required.\n')
diff_log.append('')

# ============================================================================
# Step 8 — Save v5
# ============================================================================
doc.save(str(V5))
print(f'\n[8] Saved v5_clean: {V5}')

# ============================================================================
# Step 9 — Numerical-integrity check
# ============================================================================
after_claims = extract_numbers(V5)
print(f'\n[9] Numerical-claim signatures after revision: {len(after_claims)}')

before_set = set(before_claims)
after_set  = set(after_claims)
missing = before_set - after_set
added   = after_set - before_set

diff_log.append('## Numerical-integrity guard\n')
diff_log.append(f'- v4 claim signatures: {len(before_claims)} ({len(before_set)} unique)\n')
diff_log.append(f'- v5 claim signatures: {len(after_claims)} ({len(after_set)} unique)\n')
diff_log.append(f'- Missing in v5 (potential loss): {len(missing)}\n')
diff_log.append(f'- New in v5 (potential introduction): {len(added)}\n')
if missing:
    diff_log.append('### Missing numerical signatures (v4 -> v5):\n')
    for m in sorted(missing):
        diff_log.append(f'  - `{m}`\n')
if added:
    diff_log.append('### New numerical signatures (only the band labels are expected; flag anything else):\n')
    for a in sorted(added):
        diff_log.append(f'  - `{a}`\n')
diff_log.append('')

if missing or len([a for a in added if a not in {'<25%','25–75%','>75%','25%','75%'}]) > 0:
    diff_log.append('**⚠️ Manual review required for the symbols flagged above.**\n')
    print('    ⚠️  Numerical-integrity flagged some signatures — see DIFF_LOG.md')
else:
    diff_log.append('**✅ Numerical-integrity guard passed: no headline numbers lost or unexpectedly introduced.**\n')
    print('    ✅ Numerical-integrity passed')

# ============================================================================
# Save diff log
# ============================================================================
DIFF.write_text('\n'.join(diff_log), encoding='utf-8')
print(f'\nDiff log: {DIFF}')
print('\nDone.')
