################################################################################
#                                                                              #
#  CALON-FH: UK BIOBANK EXTERNAL VALIDATION                                    #
#  STEP 02 — FROZEN-COEFFICIENT VALIDATION (TRIPOD TYPE 4)                     #
#                                                                              #
#  This is the CORE SCIENCE script. It applies:                                #
#    1. Frozen SHORYAN-CALON coefficients to UKB FH patients                   #
#    2. Frozen SAFEHEART-RE coefficients as benchmark                          #
#    3. Three-tier validation (Full / CORE / Gene-augmented)                   #
#    4. Time-to-event analysis (Cox PH, KM, competing risk)                   #
#    5. Calibration, discrimination, reclassification                          #
#    6. Subgroup and sensitivity analyses                                       #
#                                                                              #
#  Author:  Dr Nader Genedy                                                    #
#  Date:    February 2026                                                      #
#  Target:  Nature-calibre publication                                         #
#                                                                              #
################################################################################

rm(list = ls())
set.seed(2026)

# =============================================================================
# PACKAGES
# =============================================================================

required_packages <- c(
  "dplyr", "tidyr", "readr", "ggplot2", "patchwork", "scales",
  "pROC", "survival", "survminer", "rms", "cmprsk",
  "boot", "ResourceSelection", "nricens", "tableone",
  "DescTools", "CalibrationCurves", "dcurves"
)

for (pkg in required_packages) {
  if (!require(pkg, character.only = TRUE, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org")
    library(pkg, character.only = TRUE)
  }
}

cat("\n")
cat("╔══════════════════════════════════════════════════════════════════════╗\n")
cat("║  CALON-FH: UK BIOBANK FROZEN-COEFFICIENT EXTERNAL VALIDATION      ║\n")
cat("║  TRIPOD Type 4 — No Re-estimation of Coefficients                 ║\n")
cat("╚══════════════════════════════════════════════════════════════════════╝\n\n")

# =============================================================================
# CONFIGURATION
# =============================================================================

OUT_DIR <- "C:/Users/nader/Downloads/calon_ukb_pipeline/output/"
FIG_DIR <- paste0(OUT_DIR, "figures/")
TAB_DIR <- paste0(OUT_DIR, "tables/")
for (d in c(FIG_DIR, TAB_DIR)) if (!dir.exists(d)) dir.create(d, recursive = TRUE)

# ── Load analysis-ready dataset ─────────────────────────────────────────────
df <- read.csv(paste0(OUT_DIR, "calon_ukb_analysis_ready.csv"),
               stringsAsFactors = FALSE)
cat(sprintf("Loaded: %d genetically confirmed FH patients\n\n", nrow(df)))

# =============================================================================
# FROZEN CALON COEFFICIENTS
# =============================================================================
# These coefficients are FROM THE DEVELOPMENT COHORT (Wales FH Registry,
# n=424, 61 events) and are applied WITHOUT re-estimation (TRIPOD Type 4).
#
# Generated by: 99_extract_frozen_coefficients.R
# Source data:  DRAGON2.csv (Wales FH Registry)
# Model:        glm(ASCVD ~ age + re_ldl + lipid_years + log_apob_ldl +
#                   lpa_binary + inv_hdl, family = binomial)
# =============================================================================

cat("═══════════════════════════════════════════════════════════════════════\n")
cat("FROZEN COEFFICIENTS (from development cohort)\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

# ── Load frozen coefficients from CSV (produced by 99_extract_frozen_coefficients.R) ──
COEF_DIR <- "C:/Users/nader/Downloads/calon_ukb_pipeline/"

load_frozen_coefficients <- function(filepath, model_name) {
  if (file.exists(filepath)) {
    coef_df <- read.csv(filepath, stringsAsFactors = FALSE)
    coef_list <- setNames(as.list(coef_df$coefficient), coef_df$variable)
    # Rename "(Intercept)" to "intercept" for consistency
    names(coef_list)[names(coef_list) == "(Intercept)"] <- "intercept"
    cat(sprintf("  >> Loaded %s from CSV (%d coefficients)\n", model_name, length(coef_list)))
    return(coef_list)
  } else {
    cat(sprintf("  !! WARNING: %s not found. Using FALLBACK coefficients.\n", filepath))
    cat(sprintf("     Run 99_extract_frozen_coefficients.R first to generate exact values.\n"))
    return(NULL)
  }
}

# ── SHORYAN-CALON 6-variable model ──────────────────────────────────────────
CALON_COEF <- load_frozen_coefficients(
  paste0(COEF_DIR, "CALON_frozen_coefficients.csv"),
  "CALON 6-variable"
)

# Fallback if CSV not available (run 99_extract script first!)
if (is.null(CALON_COEF)) {
  cat("  Using FALLBACK coefficients — REPLACE WITH EXACT VALUES!\n")
  CALON_COEF <- list(
    intercept    = -8.500,   # FALLBACK — run 99_extract_frozen_coefficients.R
    age          =  0.065,
    re_ldl       =  0.180,
    lipid_years  =  0.055,
    log_apob_ldl =  2.500,
    lpa_binary   =  0.600,
    inv_hdl      =  0.350
  )
}

cat("\n  CALON coefficients (frozen):\n")
for (nm in names(CALON_COEF)) {
  cat(sprintf("    %-15s: %10.6f\n", nm, CALON_COEF[[nm]]))
}

# ── CALON-CORE 4-variable model (reduced, without ApoB/LDL and Lp(a)) ──────
CALON_CORE_COEF <- load_frozen_coefficients(
  paste0(COEF_DIR, "CALON_CORE_frozen_coefficients.csv"),
  "CALON-CORE 4-variable"
)

if (is.null(CALON_CORE_COEF)) {
  cat("  Using FALLBACK CORE coefficients — REPLACE WITH EXACT VALUES!\n")
  CALON_CORE_COEF <- list(
    intercept    = -7.200,
    age          =  0.070,
    re_ldl       =  0.200,
    lipid_years  =  0.060,
    inv_hdl      =  0.400
  )
}

cat("\n  CALON-CORE coefficients (frozen, reduced model):\n")
for (nm in names(CALON_CORE_COEF)) {
  cat(sprintf("    %-15s: %10.6f\n", nm, CALON_CORE_COEF[[nm]]))
}

# ── Load development variable summary for sanity checks ─────────────────────
dev_summary_file <- paste0(COEF_DIR, "CALON_development_variable_summary.csv")
if (file.exists(dev_summary_file)) {
  dev_summary <- read.csv(dev_summary_file, stringsAsFactors = FALSE)
  cat("\n  Development cohort variable ranges (for plausibility checks):\n")
  for (i in 1:nrow(dev_summary)) {
    cat(sprintf("    %-15s: mean=%.3f, SD=%.3f, range=[%.2f, %.2f]\n",
                dev_summary$variable[i], dev_summary$mean[i], dev_summary$sd[i],
                dev_summary$min[i], dev_summary$max[i]))
  }
}

# ── SAFEHEART-RE published coefficients (benchmark) ─────────────────────────
SAFEHEART_COEF <- list(
  intercept = -7.053,
  age       =  0.064,
  male      =  0.775,
  ldl_c     =  0.109,
  htn       =  0.431,
  bmi       =  0.025,
  smoking   =  0.466,
  prior_cvd =  1.414
)

cat("\n  SAFEHEART-RE coefficients (published):\n")
for (nm in names(SAFEHEART_COEF)) {
  cat(sprintf("    %-15s: %8.4f\n", nm, SAFEHEART_COEF[[nm]]))
}

# =============================================================================
# COMPUTE PREDICTED PROBABILITIES (FROZEN)
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("COMPUTING PREDICTED PROBABILITIES\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

# ── CALON Full (Tier 1) ─────────────────────────────────────────────────────
df$lp_calon <- with(df,
  CALON_COEF$intercept +
  CALON_COEF$age          * age +
  CALON_COEF$re_ldl       * re_ldl +
  CALON_COEF$lipid_years  * lipid_years_A +
  CALON_COEF$log_apob_ldl * log_apob_ldl +
  CALON_COEF$lpa_binary   * lpa_binary +
  CALON_COEF$inv_hdl      * inv_hdl
)
df$prob_calon <- 1 / (1 + exp(-df$lp_calon))

# ── CALON-CORE (Tier 2) ─────────────────────────────────────────────────────
df$lp_calon_core <- with(df,
  CALON_CORE_COEF$intercept +
  CALON_CORE_COEF$age         * age +
  CALON_CORE_COEF$re_ldl      * re_ldl +
  CALON_CORE_COEF$lipid_years * lipid_years_A +
  CALON_CORE_COEF$inv_hdl     * inv_hdl
)
df$prob_calon_core <- 1 / (1 + exp(-df$lp_calon_core))

# ── SAFEHEART-RE (benchmark) ────────────────────────────────────────────────
df$lp_safeheart <- with(df,
  SAFEHEART_COEF$intercept +
  SAFEHEART_COEF$age       * age +
  SAFEHEART_COEF$male      * sex +
  SAFEHEART_COEF$ldl_c     * ldl +
  SAFEHEART_COEF$htn       * hypertension +
  SAFEHEART_COEF$bmi       * bmi +
  SAFEHEART_COEF$smoking   * smoking_binary +
  SAFEHEART_COEF$prior_cvd * ascvd_prevalent
)
df$prob_safeheart <- 1 / (1 + exp(-df$lp_safeheart))

cat("  Predicted probabilities computed for all three models.\n")

# =============================================================================
# DISCRIMINATION ANALYSIS
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("DISCRIMINATION (AUC / C-STATISTIC)\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

# ── Tier 1: Full CALON vs SAFEHEART-RE ──────────────────────────────────────
tier1 <- df %>% filter(tier1_eligible == 1 & !is.na(ascvd_combined))

if (nrow(tier1) > 0 && sum(tier1$ascvd_combined) > 5) {
  roc_calon_t1    <- roc(tier1$ascvd_combined, tier1$prob_calon, quiet = TRUE)
  roc_safeheart_t1 <- roc(tier1$ascvd_combined, tier1$prob_safeheart, quiet = TRUE)

  cat(sprintf("  TIER 1 (Full CALON, n=%d, events=%d):\n", nrow(tier1), sum(tier1$ascvd_combined)))
  cat(sprintf("    CALON AUC:       %.3f (95%% CI %.3f-%.3f)\n",
              auc(roc_calon_t1), ci.auc(roc_calon_t1)[1], ci.auc(roc_calon_t1)[3]))
  cat(sprintf("    SAFEHEART-RE AUC: %.3f (95%% CI %.3f-%.3f)\n",
              auc(roc_safeheart_t1), ci.auc(roc_safeheart_t1)[1], ci.auc(roc_safeheart_t1)[3]))

  # DeLong test
  delong_t1 <- roc.test(roc_calon_t1, roc_safeheart_t1, method = "delong")
  cat(sprintf("    DeLong p-value:  %.6f\n", delong_t1$p.value))
  cat(sprintf("    Delta AUC:       %.3f\n", auc(roc_calon_t1) - auc(roc_safeheart_t1)))
} else {
  cat("  TIER 1: Insufficient data for analysis\n")
}

# ── Tier 2: CALON-CORE vs SAFEHEART-RE ──────────────────────────────────────
tier2 <- df %>% filter(tier2_eligible == 1 & !is.na(ascvd_combined))

if (nrow(tier2) > 0 && sum(tier2$ascvd_combined) > 5) {
  roc_core_t2      <- roc(tier2$ascvd_combined, tier2$prob_calon_core, quiet = TRUE)
  roc_safeheart_t2 <- roc(tier2$ascvd_combined, tier2$prob_safeheart, quiet = TRUE)

  cat(sprintf("\n  TIER 2 (CALON-CORE, n=%d, events=%d):\n", nrow(tier2), sum(tier2$ascvd_combined)))
  cat(sprintf("    CALON-CORE AUC:  %.3f (95%% CI %.3f-%.3f)\n",
              auc(roc_core_t2), ci.auc(roc_core_t2)[1], ci.auc(roc_core_t2)[3]))
  cat(sprintf("    SAFEHEART-RE AUC: %.3f (95%% CI %.3f-%.3f)\n",
              auc(roc_safeheart_t2), ci.auc(roc_safeheart_t2)[1], ci.auc(roc_safeheart_t2)[3]))

  delong_t2 <- roc.test(roc_core_t2, roc_safeheart_t2, method = "delong")
  cat(sprintf("    DeLong p-value:  %.6f\n", delong_t2$p.value))
  cat(sprintf("    Delta AUC:       %.3f\n", auc(roc_core_t2) - auc(roc_safeheart_t2)))
} else {
  cat("  TIER 2: Insufficient data for analysis\n")
}

# =============================================================================
# CALIBRATION ANALYSIS
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("CALIBRATION\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

calibration_metrics <- function(observed, predicted, model_name) {
  # Remove NaN/NA pairs
  valid <- !is.na(observed) & !is.na(predicted) & !is.nan(predicted)
  if (sum(valid) < 20) {
    cat(sprintf("  %s: INSUFFICIENT VALID PREDICTIONS (%d)\n", model_name, sum(valid)))
    return(NULL)
  }
  obs <- observed[valid]
  pred <- predicted[valid]

  # Clamp predictions to avoid Inf in qlogis
  pred <- pmax(pmin(pred, 1 - 1e-10), 1e-10)

  # Observed-to-expected ratio
  O <- sum(obs)
  E <- sum(pred)
  OE <- O / E

  # Calibration slope and intercept (logistic recalibration)
  recal <- tryCatch(
    glm(obs ~ offset(qlogis(pred)), family = binomial),
    error = function(e) NULL
  )
  intercept_recal <- if (!is.null(recal)) coef(recal)[1] else NA

  slope_model <- tryCatch(
    glm(obs ~ qlogis(pred), family = binomial),
    error = function(e) NULL
  )
  slope <- if (!is.null(slope_model)) coef(slope_model)[2] else NA

  # Hosmer-Lemeshow (with error protection)
  hl <- tryCatch(
    hoslem.test(obs, pred, g = 10),
    error = function(e) {
      # Try with fewer groups if 10 fails
      tryCatch(hoslem.test(obs, pred, g = 5),
               error = function(e2) list(statistic = NA, p.value = NA))
    }
  )

  # Brier score
  brier <- mean((pred - obs)^2)
  brier_max <- mean(obs) * (1 - mean(obs))
  brier_scaled <- 1 - brier / brier_max

  cat(sprintf("  %s:\n", model_name))
  cat(sprintf("    N valid predictions: %d\n", sum(valid)))
  cat(sprintf("    O/E ratio:        %.3f (O=%d, E=%.1f)\n", OE, O, E))
  cat(sprintf("    Calibration slope: %.3f (ideal=1.0)\n", slope))
  cat(sprintf("    Calibration int:   %.3f (ideal=0.0)\n", intercept_recal))
  if (!is.na(hl$statistic)) {
    cat(sprintf("    Hosmer-Lemeshow:   X²=%.2f, p=%.4f\n", hl$statistic, hl$p.value))
  } else {
    cat("    Hosmer-Lemeshow:   Could not compute (prediction distribution issue)\n")
  }
  cat(sprintf("    Brier score:       %.4f (scaled: %.3f)\n", brier, brier_scaled))

  return(data.frame(
    Model = model_name, OE_ratio = OE, Cal_slope = slope,
    Cal_intercept = intercept_recal,
    HL_chi2 = ifelse(is.na(hl$statistic), NA, hl$statistic),
    HL_p = ifelse(is.na(hl$p.value), NA, hl$p.value),
    Brier = brier, Brier_scaled = brier_scaled
  ))
}

cal_results <- list()

if (exists("roc_calon_t1")) {
  cal_results[[1]] <- calibration_metrics(tier1$ascvd_combined, tier1$prob_calon, "CALON Full (Tier 1)")
  cal_results[[2]] <- calibration_metrics(tier1$ascvd_combined, tier1$prob_safeheart, "SAFEHEART-RE (Tier 1)")
}
if (exists("roc_core_t2")) {
  cal_results[[3]] <- calibration_metrics(tier2$ascvd_combined, tier2$prob_calon_core, "CALON-CORE (Tier 2)")
  cal_results[[4]] <- calibration_metrics(tier2$ascvd_combined, tier2$prob_safeheart, "SAFEHEART-RE (Tier 2)")
}

cal_table <- bind_rows(cal_results)
write.csv(cal_table, paste0(TAB_DIR, "calibration_metrics.csv"), row.names = FALSE)

# =============================================================================
# NET RECLASSIFICATION IMPROVEMENT (NRI)
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("NET RECLASSIFICATION IMPROVEMENT\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

# Risk categories: <10%, 10-20%, >20% (clinically meaningful)
risk_cuts <- c(0, 0.10, 0.20, 1.0)

if (exists("roc_calon_t1")) {
  # Category-based NRI
  cat_old <- cut(tier1$prob_safeheart, breaks = risk_cuts, include.lowest = TRUE)
  cat_new <- cut(tier1$prob_calon, breaks = risk_cuts, include.lowest = TRUE)

  # Reclassification table
  reclass_table <- table(SAFEHEART = cat_old, CALON = cat_new, Event = tier1$ascvd_combined)
  cat("  Reclassification Table (Tier 1):\n")
  print(reclass_table)

  # Continuous NRI (using nricens if available)
  tryCatch({
    nri_result <- nricens::nribin(
      event = tier1$ascvd_combined,
      p.std = tier1$prob_safeheart,
      p.new = tier1$prob_calon,
      cut = c(0.10, 0.20),
      niter = 1000
    )
    cat("\n  Category-based NRI result:\n")
    print(nri_result)
  }, error = function(e) {
    cat(sprintf("  NRI calculation error: %s\n", e$message))
  })
}

# =============================================================================
# GENE-STRATIFIED ANALYSIS (TIER 3)
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("GENE-STRATIFIED ANALYSIS (TIER 3)\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

for (g in c("LDLR", "APOB", "PCSK9")) {
  subset_g <- df %>% filter(gene == g & tier2_eligible == 1 & !is.na(ascvd_combined))
  if (nrow(subset_g) > 20 && sum(subset_g$ascvd_combined) >= 5) {
    roc_g <- roc(subset_g$ascvd_combined, subset_g$prob_calon_core, quiet = TRUE)
    cat(sprintf("  %s (n=%d, events=%d): AUC %.3f (%.3f-%.3f)\n",
                g, nrow(subset_g), sum(subset_g$ascvd_combined),
                auc(roc_g), ci.auc(roc_g)[1], ci.auc(roc_g)[3]))
  } else {
    cat(sprintf("  %s: Insufficient data (n=%d, events=%d)\n",
                g, nrow(subset_g), sum(subset_g$ascvd_combined)))
  }
}

# =============================================================================
# SUBGROUP ANALYSES
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("SUBGROUP ANALYSES\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

subgroup_auc <- function(subset_df, label) {
  if (nrow(subset_df) > 20 && sum(subset_df$ascvd_combined, na.rm=T) >= 5) {
    r <- roc(subset_df$ascvd_combined, subset_df$prob_calon_core, quiet = TRUE)
    cat(sprintf("  %s (n=%d, events=%d): AUC %.3f\n",
                label, nrow(subset_df), sum(subset_df$ascvd_combined, na.rm=T), auc(r)))
  } else {
    cat(sprintf("  %s: Insufficient events\n", label))
  }
}

# By sex
subgroup_auc(df %>% filter(sex == 1 & tier2_eligible == 1), "Male")
subgroup_auc(df %>% filter(sex == 0 & tier2_eligible == 1), "Female")

# By age
subgroup_auc(df %>% filter(age < 55 & tier2_eligible == 1), "Age <55")
subgroup_auc(df %>% filter(age >= 55 & tier2_eligible == 1), "Age >=55")

# By statin status
subgroup_auc(df %>% filter(on_statin == 1 & tier2_eligible == 1), "On statin")
subgroup_auc(df %>% filter(on_statin == 0 & tier2_eligible == 1), "No statin")

# Prevalent vs incident
subgroup_auc(df %>% filter(ascvd_prevalent == 0 & tier2_eligible == 1), "Primary prevention only")

# =============================================================================
# TIME-TO-EVENT ANALYSIS (INCIDENT EVENTS ONLY)
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("TIME-TO-EVENT ANALYSIS (INCIDENT ASCVD)\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

# Restrict to primary prevention (no prevalent ASCVD) for survival analysis
pp <- df %>% filter(ascvd_prevalent == 0 & !is.na(followup_years) & followup_years > 0)

if (nrow(pp) > 20) {
  # Risk tertiles based on CALON-CORE predicted probability
  pp$risk_tertile <- cut(pp$prob_calon_core,
                         breaks = quantile(pp$prob_calon_core, c(0, 1/3, 2/3, 1), na.rm=T),
                         labels = c("Low", "Medium", "High"),
                         include.lowest = TRUE)

  # Kaplan-Meier by risk tertile
  surv_obj <- Surv(pp$followup_years, pp$event_indicator)
  km_fit <- survfit(surv_obj ~ risk_tertile, data = pp)

  cat("  Kaplan-Meier estimates by CALON risk tertile:\n")
  print(summary(km_fit, times = c(5, 10, 15)))

  # Log-rank test
  lr_test <- survdiff(surv_obj ~ risk_tertile, data = pp)
  cat(sprintf("\n  Log-rank test: X²=%.2f, p=%.6f\n", lr_test$chisq,
              1 - pchisq(lr_test$chisq, length(lr_test$n) - 1)))

  # Cox proportional hazards with CALON linear predictor
  cox_calon <- coxph(surv_obj ~ lp_calon_core, data = pp)
  cat("\n  Cox model (CALON-CORE linear predictor):\n")
  cat(sprintf("    Concordance (C-index): %.3f\n", concordance(cox_calon)$concordance))
  print(summary(cox_calon))

  # Harrell's C-statistic comparison
  cox_safeheart <- coxph(surv_obj ~ lp_safeheart, data = pp)
  cat(sprintf("\n  SAFEHEART-RE C-index: %.3f\n", concordance(cox_safeheart)$concordance))

  # Save KM plot
  p_km <- ggsurvplot(km_fit, data = pp,
                     palette = c("#2E74B5", "#70AD47", "#C00000"),
                     legend.title = "CALON Risk Category",
                     legend.labs = c("Low risk", "Medium risk", "High risk"),
                     xlab = "Follow-up (years)",
                     ylab = "ASCVD-free survival",
                     risk.table = TRUE,
                     risk.table.height = 0.25,
                     conf.int = TRUE,
                     ggtheme = theme_minimal(),
                     title = "ASCVD-Free Survival by CALON Risk Category\nUK Biobank Genetically Confirmed FH")

  ggsave(paste0(FIG_DIR, "Figure_KM_CALON_risk.png"), plot = print(p_km),
         width = 10, height = 8, dpi = 300)
  ggsave(paste0(FIG_DIR, "Figure_KM_CALON_risk.pdf"), plot = print(p_km),
         width = 10, height = 8)
  cat("  ✓ KM plot saved\n")
}

# =============================================================================
# DECISION CURVE ANALYSIS
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("DECISION CURVE ANALYSIS\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

tryCatch({
  dca_data <- df %>%
    filter(tier2_eligible == 1 & !is.na(ascvd_combined)) %>%
    select(ascvd_combined, prob_calon_core, prob_safeheart) %>%
    rename(outcome = ascvd_combined, CALON_CORE = prob_calon_core, SAFEHEART = prob_safeheart)

  dca_result <- dca(outcome ~ CALON_CORE + SAFEHEART,
                    data = dca_data,
                    thresholds = seq(0, 0.50, by = 0.01))

  p_dca <- plot(dca_result) +
    labs(title = "Decision Curve Analysis: CALON-CORE vs SAFEHEART-RE",
         subtitle = "UK Biobank Genetically Confirmed FH") +
    theme_minimal()

  ggsave(paste0(FIG_DIR, "Figure_DCA.png"), p_dca, width = 10, height = 7, dpi = 300)
  cat("  ✓ DCA plot saved\n")
}, error = function(e) {
  cat(sprintf("  DCA error: %s\n", e$message))
})

# =============================================================================
# SENSITIVITY ANALYSES
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("SENSITIVITY ANALYSES\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

# ── Sensitivity 1: Age-at-treatment scenarios ───────────────────────────────
cat("  1. Age-at-treatment sensitivity (lipid-year scenarios):\n")
for (scenario in c("A", "B", "C")) {
  ly_col <- paste0("lipid_years_", scenario)
  df$lp_sens <- with(df,
    CALON_CORE_COEF$intercept +
    CALON_CORE_COEF$age         * age +
    CALON_CORE_COEF$re_ldl      * re_ldl +
    CALON_CORE_COEF$lipid_years * df[[ly_col]] +
    CALON_CORE_COEF$inv_hdl     * inv_hdl
  )
  df$prob_sens <- 1 / (1 + exp(-df$lp_sens))

  sens_df <- df %>% filter(tier2_eligible == 1 & !is.na(ascvd_combined))
  if (sum(sens_df$ascvd_combined) >= 5) {
    roc_sens <- roc(sens_df$ascvd_combined, sens_df$prob_sens, quiet = TRUE)
    cat(sprintf("    Scenario %s: AUC %.3f\n", scenario, auc(roc_sens)))
  }
}

# ── Sensitivity 2: Exclude prevalent events ─────────────────────────────────
cat("\n  2. Incident-only analysis (exclude prevalent ASCVD):\n")
incident_only <- df %>%
  filter(ascvd_prevalent == 0 & tier2_eligible == 1 & !is.na(ascvd_incident))
if (sum(incident_only$ascvd_incident) >= 5) {
  roc_inc <- roc(incident_only$ascvd_incident, incident_only$prob_calon_core, quiet = TRUE)
  cat(sprintf("    CALON-CORE AUC (incident only): %.3f (n=%d, events=%d)\n",
              auc(roc_inc), nrow(incident_only), sum(incident_only$ascvd_incident)))
}

# ── Sensitivity 3: Statin-adjusted LDL assumption ──────────────────────────
cat("\n  3. Alternative residual factor assumptions:\n")
for (rf_adjust in c(0.9, 1.0, 1.1)) {
  df$re_ldl_alt <- df$ldl / (df$residual_factor * rf_adjust)
  df$lp_alt <- with(df,
    CALON_CORE_COEF$intercept +
    CALON_CORE_COEF$age         * age +
    CALON_CORE_COEF$re_ldl      * re_ldl_alt +
    CALON_CORE_COEF$lipid_years * (re_ldl_alt * pmax(0, age_treatment_A - 18) / 10) +
    CALON_CORE_COEF$inv_hdl     * inv_hdl
  )
  df$prob_alt <- 1 / (1 + exp(-df$lp_alt))
  alt_df <- df %>% filter(tier2_eligible == 1 & !is.na(ascvd_combined))
  if (sum(alt_df$ascvd_combined) >= 5) {
    roc_alt <- roc(alt_df$ascvd_combined, alt_df$prob_alt, quiet = TRUE)
    cat(sprintf("    RF multiplier %.1f: AUC %.3f\n", rf_adjust, auc(roc_alt)))
  }
}

# =============================================================================
# TABLE 1: BASELINE CHARACTERISTICS
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("TABLE 1: BASELINE CHARACTERISTICS\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

table1_vars <- c("age", "sex", "bmi", "waist", "sbp",
                 "tc", "ldl", "hdl", "trig", "apob", "lpa",
                 "re_ldl", "lipid_years_A", "apob_ldl_ratio", "log_apob_ldl",
                 "on_statin", "hypertension", "diabetes", "smoking_binary",
                 "ascvd_combined", "ascvd_prevalent", "ascvd_incident")

table1_cat <- c("sex", "on_statin", "hypertension", "diabetes", "smoking_binary",
                "ascvd_combined", "ascvd_prevalent", "ascvd_incident")

t1 <- CreateTableOne(vars = table1_vars, factorVars = table1_cat,
                     strata = "gene", data = df, addOverall = TRUE)
t1_print <- print(t1, nonnormal = c("lpa", "trig"), printToggle = FALSE)
write.csv(t1_print, paste0(TAB_DIR, "table1_baseline.csv"))
cat("  ✓ Table 1 saved\n")
print(t1)

# =============================================================================
# SUMMARY RESULTS TABLE
# =============================================================================

cat("\n═══════════════════════════════════════════════════════════════════════\n")
cat("SUMMARY RESULTS\n")
cat("═══════════════════════════════════════════════════════════════════════\n\n")

results_summary <- data.frame(
  Analysis = character(),
  N = integer(),
  Events = integer(),
  CALON_AUC = numeric(),
  SAFEHEART_AUC = numeric(),
  Delta_AUC = numeric(),
  P_value = numeric(),
  stringsAsFactors = FALSE
)

# Populate from computed results
if (exists("roc_calon_t1")) {
  results_summary <- rbind(results_summary, data.frame(
    Analysis = "Tier 1: Full CALON",
    N = nrow(tier1), Events = sum(tier1$ascvd_combined),
    CALON_AUC = round(auc(roc_calon_t1), 3),
    SAFEHEART_AUC = round(auc(roc_safeheart_t1), 3),
    Delta_AUC = round(auc(roc_calon_t1) - auc(roc_safeheart_t1), 3),
    P_value = round(delong_t1$p.value, 6)
  ))
}

if (exists("roc_core_t2")) {
  results_summary <- rbind(results_summary, data.frame(
    Analysis = "Tier 2: CALON-CORE",
    N = nrow(tier2), Events = sum(tier2$ascvd_combined),
    CALON_AUC = round(auc(roc_core_t2), 3),
    SAFEHEART_AUC = round(auc(roc_safeheart_t2), 3),
    Delta_AUC = round(auc(roc_core_t2) - auc(roc_safeheart_t2), 3),
    P_value = round(delong_t2$p.value, 6)
  ))
}

write.csv(results_summary, paste0(TAB_DIR, "results_summary.csv"), row.names = FALSE)
cat("  Results summary:\n")
print(results_summary)

cat("\n╔══════════════════════════════════════════════════════════════════════╗\n")
cat("║  VALIDATION COMPLETE                                              ║\n")
cat("║                                                                    ║\n")
cat("║  CRITICAL: Replace PLACEHOLDER coefficients with exact values     ║\n")
cat("║  from DRAGON2.csv model fit before publication.                    ║\n")
cat("║                                                                    ║\n")
cat("║  Output files in: calon_ukb_pipeline/output/                      ║\n")
cat("╚══════════════════════════════════════════════════════════════════════╝\n")
