library(haven)
p <- read_sav("C:/Users/nader/Downloads/calon_ukb_pipeline/PASS_wrong_dob.sav")
cat("Positive1 class:", class(p[["Positive1"]]), "\n")
cat("Positive1 values:\n")
print(table(as.character(p[["Positive1"]]), useNA="ifany"))
cat("\nI_Vs_R class:", class(p[["I_Vs_R"]]), "\n")
cat("I_Vs_R values:\n")
print(table(as.character(p[["I_Vs_R"]]), useNA="ifany"))
cat("\nGender values:\n")
print(table(as.character(p[["Gender"]]), useNA="ifany"))
cat("\nBMI_AGE summary:\n")
print(summary(as.numeric(p[["BMI_AGE"]])))
cat("\nTreatment1.1 non-NA:", sum(!is.na(p[["Treatment1.1"]])), "\n")
cat("GenoTypingScore non-NA:", sum(!is.na(p[["GenoTypingScore"]])), "\n")
