d <- read.csv("DRAGON_3.csv")
cat("N:", nrow(d), "\n")
cat("ASCVD:", sum(d$ASCVD_combined==1, na.rm=TRUE), "\n")
cat("APOB_LDL summary:\n")
print(summary(d$APOB_LDL))
sub <- d[is.finite(d$APOB_LDL) & d$APOB_LDL > 0, ]
cat("N with APOB_LDL:", nrow(sub), "\n")
cat("ASCVD in subset:", sum(sub$ASCVD_combined==1, na.rm=TRUE), "\n")
cat("Gender:", paste(unique(d$Gender), collapse=", "), "\n")
cat("DM:", paste(unique(d$Diabetes_binary), collapse=", "), "\n")
cat("Smoking:", paste(unique(d$Smoking_binary), collapse=", "), "\n")
cat("BMI range:", paste(range(d$BMI, na.rm=TRUE), collapse=" - "), "\n")
cat("Statin:", paste(unique(d$Statin)[1:5], collapse=", "), "\n")
cat("Age col:", paste(unique(d$age_at_event_or_censoring)[1:5], collapse=", "), "\n")
cat("LDL:", paste(range(d$LastLDL, na.rm=TRUE), collapse=" - "), "\n")
cat("HDL:", paste(range(d$LastHDL, na.rm=TRUE), collapse=" - "), "\n")
cat("TRG:", paste(range(d$LastTrigs, na.rm=TRUE), collapse=" - "), "\n")
