d <- read.csv("calon_ukb_analysis_ready.csv")
cat("N:", nrow(d), "\n")
cat("Columns with apob:\n")
cat(grep("apob", names(d), value=TRUE, ignore.case=TRUE), sep="\n")
cat("\napob_ldl_ratio summary:\n")
print(summary(d$apob_ldl_ratio))
cat("N with apob_ldl >0:", sum(is.finite(d$apob_ldl_ratio) & d$apob_ldl_ratio > 0), "\n")
cat("ASCVD:", sum(d$ascvd_combined==1, na.rm=TRUE), "\n")
cat("diabetes:", sum(d$diabetes==1, na.rm=TRUE), "\n")
cat("on_statin:", sum(d$on_statin==1, na.rm=TRUE), "\n")
cat("age range:", paste(range(d$age, na.rm=TRUE), collapse=" - "), "\n")
cat("bmi range:", paste(range(d$bmi, na.rm=TRUE), collapse=" - "), "\n")
cat("trig range:", paste(range(d$trig, na.rm=TRUE), collapse=" - "), "\n")
