suppressPackageStartupMessages({library(tidyverse);library(pROC)})
pred <- read_csv('C:/Users/nader/Downloads/calon_ukb_pipeline/tudor_loco_output/loco_predictions_complete.csv', show_col_types=FALSE)
cat('n=',nrow(pred),'fh=',sum(pred$fh),'\n')
cat('cohorts=',paste(unique(pred$cohort),collapse=','),'\n')
wales <- filter(pred, grepl('Wales',cohort))
sw    <- filter(pred, cohort=='SouthWales')
ukb   <- filter(pred, cohort=='UKB')
cat('wales_total=',nrow(wales),'fh=',sum(wales$fh),'\n')
cat('sw=',nrow(sw),'fh=',sum(sw$fh),'\n')
cat('ukb=',nrow(ukb),'fh=',sum(ukb$fh),'\n')
cat('auc_sw=',   round(as.numeric(auc(roc(sw$fh, sw$pred, quiet=TRUE))),4),'\n')
cat('auc_wales=',round(as.numeric(auc(roc(wales$fh,wales$pred,quiet=TRUE))),4),'\n')
cat('dlcn_auc=', round(as.numeric(auc(roc(wales$fh,wales$dlcn,quiet=TRUE))),4),'\n')
cat('age_mean=',round(mean(pred$age,na.rm=TRUE),1),'sd=',round(sd(pred$age,na.rm=TRUE),1),'\n')
cat('female_pct=',round(100*mean(pred$sex==0,na.rm=TRUE),1),'\n')
cat('statin_pct=',round(100*mean(pred$on_statin,na.rm=TRUE),1),'\n')
cat('index_pct=',round(100*mean(pred$index_case,na.rm=TRUE),1),'\n')
cat('ldlr=',sum(pred$gene=='LDLR',na.rm=TRUE),'\n')
cat('apob=',sum(pred$gene=='APOB',na.rm=TRUE),'\n')
cat('pcsk9=',sum(pred$gene=='PCSK9',na.rm=TRUE),'\n')
cat('mean_ldl_ut=',round(mean(pred$ldl_ut,na.rm=TRUE),2),'sd=',round(sd(pred$ldl_ut,na.rm=TRUE),2),'\n')
cat('mean_dlcn=',round(mean(pred$dlcn,na.rm=TRUE),1),'\n')
cat('mean_tg=',round(mean(pred$tg,na.rm=TRUE),2),'\n')
cat('mean_hdl=',round(mean(pred$hdl,na.rm=TRUE),2),'\n')
fhpos <- filter(pred, fh==1)
cat('\nFH+ n=',nrow(fhpos),'\n')
cat('FH+ mean_ldl=',round(mean(fhpos$ldl_ut,na.rm=TRUE),2),'sd=',round(sd(fhpos$ldl_ut,na.rm=TRUE),2),'\n')
cat('FH+ mean_age=',round(mean(fhpos$age,na.rm=TRUE),1),'\n')
cat('FH+ female=',round(100*mean(fhpos$sex==0,na.rm=TRUE),1),'\n')
cat('FH+ statin=',round(100*mean(fhpos$on_statin,na.rm=TRUE),1),'\n')
cat('FH+ gene: LDLR=',sum(fhpos$gene=='LDLR',na.rm=TRUE),
    'APOB=',sum(fhpos$gene=='APOB',na.rm=TRUE),
    'PCSK9=',sum(fhpos$gene=='PCSK9',na.rm=TRUE),'\n')
# FH- group
fhneg <- filter(pred, fh==0)
cat('\nFH- n=',nrow(fhneg),'\n')
cat('FH- mean_ldl=',round(mean(fhneg$ldl_ut,na.rm=TRUE),2),'sd=',round(sd(fhneg$ldl_ut,na.rm=TRUE),2),'\n')
cat('FH- mean_age=',round(mean(fhneg$age,na.rm=TRUE),1),'\n')
cat('FH- female=',round(100*mean(fhneg$sex==0,na.rm=TRUE),1),'\n')
cat('FH- statin=',round(100*mean(fhneg$on_statin,na.rm=TRUE),1),'\n')
